services:
  qdrant_db:
    container_name: qdrant_test
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6334:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file:
      - .env
    networks:
      - network

  postgres_db:
    container_name: postgres_test
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres:
  qdrant_storage: