services:

  api:
    container_name: api
    build: .
    image: wrola0/personal-api:latest
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - postgres_db
      - qdrant_db
    networks:
      - network

  qdrant_db:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file:
      - .env
    networks:
      - network

  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres:
  qdrant_storage: