version: '3.9'

services:

  api:
    container_name: api
    build: .
    image: wrola0/personal-api:latest
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.lifecycle.post-update="npm run migration:run"
    networks:
      - network

  qdrant_db:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file:
      - .env
    networks:
      - network

  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    networks:
      - network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=${REPO_USER}
      - REPO_PASS=${REPO_PASS}
    command: --interval 30

networks:
  network:
    driver: bridge

volumes:
  postgres:
  qdrant_storage: