version: '3.9'

services:

  api:
    container_name: api
    build: .
    image: api
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    networks:
      - network

  qdrant_db:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file:
      - .env
    networks:
      - network

  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    networks:
      - network

  watchtower:
    image: containrrr/watchtower
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

networks:
  network:
    driver: bridge

volumes:
  postgres:
  qdrant_storage: